server.port=${PORT:8080}
spring.application.name=othello
spring.jmx.enabled=false
spring.sql.init.mode=never

spring.datasource.url=jdbc:${DATABASE_PUBLIC_URL}?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.maximum-pool-size=2

spring.main.lazy-initialization=false
