server.port=${PORT:8080}
spring.application.name=othello
spring.jmx.enabled=false
spring.sql.init.mode=never

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=2

# lazy-initをオフにして@PostConstructを確実に実行
spring.main.lazy-initialization=false
